### ISSUE TITLE
Hello, author. I have a request

### ISSUE THREAD

**Issue by cnluminous** [seppukudevelopment/seppuku#14]
I hope to extract the TP function in seppuku, but I can't compile normally. Can you help me?

**Comment by cookiedragon234** [comment]
What

**Comment by cnluminous** [comment]
Already not needed, how can I modify the instruction prefix?

**Comment by cookiedragon234** [comment]
Are you talking about the command prefix? I believe you can use `.cmd prefix [new prefix]`

**Comment by Cuhnt** [comment]
I would recommend using the [seppuku discord server](https://discordapp.com/invite/nf8Dfj4) to ask for support, instead of creating an issue.
