### ISSUE TITLE
Duplicated resources when Gradle builds

### ISSUE THREAD

**Issue by ghost** [seppukudevelopment/seppuku#16]
https://github.com/seppukudevelopment/seppuku/blob/5ecfa1183d368290e71d6bacc85f3ad996227a1c/build.gradle#L125-L131

This causes duplicated resource entries when the binaries are being compiled.  I have no issues at all running the client when this is removed, does anyone else?

**Comment by noil755** [comment]
Client will run fine with or without, this was added as a fix for ForgeGradle when loading resources at runtime from the resources directory, without it the resource directory never loads when running in IDE, simply change the buildmode variable at the top of build.gradle to RELEASE and run gradle clean and then gradle build

**Comment by ethug** [comment]
Weird, I'm unable to run from the IDE with the lines added but I can run it fine without them.  I'll do some more testing, then.

**Comment by jvyden420** [comment]
This usually happens when you try to build without using gradlew. Removing the /build folder and building again fixes it for me.

**Comment by ethug** [comment]
Not the solution for this problem, unfortunately.  The duplicated resources will always be there because of these lines...

https://github.com/seppukudevelopment/seppuku/blob/5ecfa1183d368290e71d6bacc85f3ad996227a1c/build.gradle#L125-L131

I just removed the lines in my own file and won't push it.  Everything seems to work fine.

**Comment by ethug** [comment]
For sake of the repository and clearing issues and since no one else has come up with anything, I'm closing this.  Deleting the lines still works fine and has no issues with resources when building an artifact.

**Comment by ethug** [comment]
This issue came up inside of the Discord finally, so we should address it and figure out what's exactly going on.  We shouldn't need these lines at all, ForgeGradle should be doing all of that for us?

**Comment by uoil** [comment]
Closing as the client builds fine. If you change to "RELEASE" in build.gradle, clear the cache with the gradle command, run gradle build. If that does not succeed do as above and remove the lines in the post above.
