### ISSUE TITLE
Cant build

### ISSUE THREAD

**Issue by CRTCTY** [seppukudevelopment/seppuku#24]
AddPlayerData causes a problem for me. Without the JoinLeaveManager it compiles just fine.
![CantCompile](https://user-images.githubusercontent.com/58356991/71307141-3e22aa00-23ea-11ea-947d-dddc7e7912a6.png)

**Comment by ethug** [comment]
Apologies for the late reply, have you been able to fix the issue?  What commands have you run in the workspace before compiling?

**Comment by ethug** [comment]
According to another developer:  this error only happens when you haven't ran the `setupDecompWorkspace` Gradle task.  Try compiling again using the instructions in the readme, if it still does not work, please open another issue explaining in detail what you did, thank you!
