### ISSUE TITLE
Suggestion: add the ability to make the hud elements not change position upon window resize

### ISSUE THREAD

**Issue by BlazeWarfare** [seppukudevelopment/seppuku#29]
one thing I've noticed is when I minimize my mc window or resize it all the hud elements get flung inside the tiny box and in the case of the hud editor, this makes module boxes overlap and makes it unable to move them around without going into the hud config file and changing their positions in there. I suggest the ability to make it so this will no longer happen with window resizes.

**Comment by uoil** [comment]
you can now middle click any Hud component to "lock" it from clamping when resized 😄
