### ISSUE TITLE
Task :recompileMc FAILED

### ISSUE THREAD

**Issue by xphoenixd** [seppukudevelopment/seppuku#30]
After I run gradlew.bat setupDecompWorkspace, i get the error
> Task :recompileMc FAILED

FAILURE: Build failed with an exception.

**Comment by noil755** [comment]
Could you provide a log of the error?

**Comment by Zipdox** [comment]
@xphoenixd maybe this will help https://github.com/MinecraftForge/ForgeGradle/issues/459
