### ISSUE TITLE
Position lost/reset to 0,0,0 with ElytraFly

### ISSUE THREAD

**Issue by casKd-dev** [seppukudevelopment/seppuku#32]
While flying with elytra, everything seems to be working correctly unless the pitch is approx. under -85deg (looking up). From that angle, the position is reset to 0,0,0 and the player is kicked with a "Invalid move player packet received".
<details>
  <summary>Relevant debug output</summary>

```
SEND: Current pitch is -69.3
SEND: Current position is 165.960422838051 111.94959422472387 136.66349209187254
SEND: Current pitch is -69.3
SEND: Current position is 165.96007204319102 111.88229780125621 136.6628057017657
SEND: Current pitch is -69.3
SEND: Current position is 165.95972124833105 111.81500137778856 136.66211931165887
SEND: Current pitch is -70.20001
SEND: Current position is 165.95939085506015 111.74705893764049 136.66148489608048
SEND: Current pitch is -77.40001
SEND: Current position is 165.95923455434314 111.674727342671 136.661213855332
SEND: Current pitch is -87.15001
SEND: Current position is 165.9592257337944 111.59942704416625 136.66119992616447
SEND: Current pitch is -90.0
SEND: Current position is 0.0 0.0 0.0
SEND: Current pitch is -90.0
SEND: Current position is 0.0 0.0 0.0
SEND: Current pitch is -90.0
SEND: Current position is 0.0 0.0 0.0
SEND: Current pitch is -90.0
SEND: Current position is 0.0 0.0 0.0
SEND: Current pitch is -90.0
SEND: Current position is NaN 110.09022701530415 NaN
caskd lost connection: Invalid move player packet received
caskd left the game
```
</details>

Here it is clear that once the pitch is -90deg the position is lost/reset.

I assume this is due to the behavior of Elytras, as the player stops flying when the velocity is too low and they look up.

**Comment by HAV0X1014** [comment]
this is an issue with optifine. this even happens in singleplayer. turn off fast math in optifine and see if it gets fixed.

**Comment by casKd-dev** [comment]
> this is an issue with optifine

I can confirm that i cannot reproduce this without optifine. Thanks for looking into it. Closing.
