### ISSUE TITLE
I can't set it up

### ISSUE THREAD

**Issue by ragw453** [seppukudevelopment/seppuku#39]
I'm probably doing something stupid but I changed the build.gradle setting "build" from IDE to release, I ran the gradle.bat and I got this
![image](https://user-images.githubusercontent.com/62028969/84145916-ad509100-aa52-11ea-899a-b9c511087c75.png)
usually, this goes past to quickly to see, but I put a pause under the :fail section so i could see what it said I think its because I didn't run setupDecompWorkspace  and Build but I don't know where to run them

This is because I got error 404 whilst trying to get on to the website so I can download the .jar and chuck it in my mods folder

**Comment by noil755** [comment]
Ensure you have JDK 8 installed and if so already, try this:
Open a terminal/command-prompt up inside of the repository folder. Once there, run the `gradlew.bat setupDecompWorkspace` command if on Windows or `gradlew setupDecompWorkspace` on Linux. Afterwards, you should be able to run build as well.

Most IDE software handles this with Gradle integration in the UI, you'll need to import the Seppuku directory as a Gradle project within the IDE to get that level of functionality.

**Comment by uoil** [comment]
Closing this issue since there's been no follow up for a while, feel free to re-open if you continue getting this error after trying efforts found in my previous reply.
