### ISSUE TITLE
MiddleClickPearl

### ISSUE THREAD

**Issue by luyten-h** [seppukudevelopment/seppuku#44]
If you have a pearl in your hotbar and you middle click in the air, it throws a pearl.

**Comment by theluyten** [comment]
new module ^^

**Comment by Old-Chum** [comment]
I just tested this and it does not happen, are you sure that you dont have middle click bound to use? If so, what modules do you have on, and are you using the current version of seppuku?

**Comment by theluyten** [comment]
Old-Chum, this is a new module idea.

**Comment by jvyden420** [comment]
Seems simple enough. I'll work on this later today.
