### ISSUE TITLE
incompatible

### ISSUE THREAD

**Issue by martypower2064** [seppukudevelopment/seppuku#46]
so uh my minecraft wont start bc idk y 

here mods list : 
-better chat 1.4
-latest kami
-atom utility client
-salhack 2.04
-bspkrscore-universal-8.0.1
-aple skin 1.12.2-1.0.14
-ding
-enchantements descriptions
-gish code 1.12.2-v0.4.9
-GobbleCore-1.12-0.1.6.35
-infinity editor 0.14.2
-keepmykeys
-keystrokes 7.0
-keywizard
-prespectivemodredux
-quickhotbar
-resource pack organizer
-scroolable tooltips
-ghostwriter
-controling
-forgehax
-ikiwd
-impact 4.9.1
-inv tweaks
-jei
-journeymap
-mine menu
-mouse tweaks
-optifine
- world downloader
-world handler

the error is exit error : 0
and i just doesnt start pls help or no gud review 

here is pack
http://www.mediafire.com/file/8ryxwx3oxcu4hs8/mods.zip/file

**Comment by Detergent13** [comment]
Seppuku is known to be incompatible with Impact, and is likely incompatible with some of your other clients/mods as well. The incompatibility will not be fixed, as it's an issue on Impact's end.

If you want to make it work, you'll have to take the time to disable mod-by-mod until it stops crashing. 

For low-level support like this, please use the Discord server in the future! https://discord.gg/hzem5fn
