### ISSUE TITLE
Fix Crystalaura

### ISSUE THREAD

**Issue by 3arthqu4ke** [seppukudevelopment/seppuku#5]
282
damage = Math.max(damage - entity.getAbsorptionAmount(), 0.0F);

this line kinda retarded ngl, Crystalaura wont place if enemyhealth is above 20 and mindamage is lower than the amount of absorption he has.

**Comment by ethug** [comment]
File says @Rigamortis is the author of the Crystal Aura.  If he doesn't respond, I'll just remove that.

**Comment by Rigamortis** [comment]
I've been too lazy to get around to it. I do plan on rewriting CrystalAura entirely at some point.

**Comment by uoil** [comment]
Closing as there has no been replies in almost a year.
