### ISSUE TITLE
Seppuku not being compatible with Konas

### ISSUE THREAD

**Issue by FIshyZero** [seppukudevelopment/seppuku#57]

**Comment by uoil** [comment]
We don't promise support for multi-client compatibility, send us your crash log please and we may be able to help.

**Comment by uoil** [comment]
Another user has mentioned that the latest version of Seppuku does work with the client you are trying, could be user error?

**Comment by JayH4x** [comment]
![image0](https://user-images.githubusercontent.com/59585480/124348380-f3176300-dc2c-11eb-9be2-ea755ca5c94c.jpg)
