### ISSUE TITLE
Cant Build

### ISSUE THREAD

**Issue by JayH4x** [seppukudevelopment/seppuku#73]
![clean](https://user-images.githubusercontent.com/59585480/124343360-28f91f00-dc0e-11eb-99cb-7996714fb5f6.png)
pls help

**Comment by AcaiBerii** [comment]
pls get brain

**Comment by Doogie13** [comment]
have you done `setupdecompworkspace` yet?

**Comment by uoil** [comment]
Closing as nothing has been said for a while on this issue.
