### ISSUE TITLE
aint building chef

### ISSUE THREAD

**Issue by master7720** [seppukudevelopment/seppuku#89]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':reobfJar'.
> java.util.zip.ZipException: duplicate entry: assets/seppukumod/shaders/chams.frag

**Comment by uoil** [comment]
Windows
./gradlew.bat clean
./gradlew.bat build
Linux
./gradlew clean
./gradlew build

**Comment by master7720** [comment]
ah
