### ISSUE TITLE
still aint building

### ISSUE THREAD

**Issue by master7720** [seppukudevelopment/seppuku#91]
^
  bad class file: C:\Users\tracy\OneDrive\Desktop\seppuku-master\.gradle\minecraft\forgeBin-1.12.2-14.23.5.2847-PROJECT(seppuku-master).jar(net/minecraft/network/play/server/SPacketPlayerListItem$AddPlayerData.class)
    bad RuntimeInvisibleParameterAnnotations attribute: AddPlayerData(GameProfile,int,GameType,ITextComponent)
    Please remove or make sure it appears in the correct subdirectory of the classpath.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.8.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 3s
9 actionable tasks: 9 executed

C:\Users\tracy\OneDrive\Desktop\seppuku-master>

**Comment by uoil** [comment]
Running the commands in correct order as listed in the readme will result in a successful build. Thd above error only happens if you haven't ran the Gradle command setupDecompWorkspace & refreshed the workspace

**Comment by master7720** [comment]
*bruh.exe has stop*

**Comment by uoil** [comment]
Everything you need to know on how to build is in the readme, the auto-build bot is building the latest commit perfectly fine.

**Comment by HAV0X1014** [comment]
usually i find that changing buildmode to RELEASE before running any commands works best

**Comment by LiquidSmokeBalls** [comment]
are u gonna put a pull request saying Update mcmod.info and proceed to fuck the client over 😐

**Comment by bush-did-711** [comment]
💀
