### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by Watermelon1245** [seppukudevelopment/seppuku#93]
1. How do set a prefix?                                                                                                                                                                                          2. How do i make the gui size smaller?                                                                                                                                                                              3.How do i bind click gui to something else than grave and rshift? (i want only 1 key)                                                                                              That should be all

**Comment by Watermelon1245** [comment]
I figured out how to bind modules, but i dont know how to remove the bind from rshift

**Comment by Detergent13** [comment]
All answered in the [wiki](https://github.com/seppukudevelopment/seppuku/wiki).

**Comment by Watermelon1245** [comment]
yes, but the rshift clickgui bind never leaves

**Comment by Detergent13** [comment]
`.macro remove hudeditortoggle`

**Comment by Watermelon1245** [comment]
ty
