### ISSUE TITLE
How to build the client?

### ISSUE THREAD

**Issue by PiotrekUnityDeveloper** [seppukudevelopment/seppuku#95]
![image](https://user-images.githubusercontent.com/85606121/151205060-a37cac91-ebfb-46cc-98b1-29937d4a6688.png)

how can i fix that?

**Comment by uoil** [comment]
Which JDK java version are you building with?

**Comment by PiotrekUnityDeveloper** [comment]
![image](https://user-images.githubusercontent.com/85606121/151223293-274a51cf-b924-49ca-b2d9-6d1e3605066c.png)

**Comment by PiotrekUnityDeveloper** [comment]
should i use jdk 8?

**Comment by uoil** [comment]
Yes, use JDK 8 and follow the readme build guide and you should compile just fine

**Comment by PiotrekUnityDeveloper** [comment]
![image](https://user-images.githubusercontent.com/85606121/151228097-934fc545-41e2-43c2-ae06-7e8f10f79b77.png)

**Comment by uoil** [comment]
You have to run setupDecompWorkspace and refresh the Gradle project before you build

**Comment by PiotrekUnityDeveloper** [comment]
I dont that and it still shows an error 
![image](https://user-images.githubusercontent.com/85606121/151231672-5f117009-6d98-422d-8845-0ca38a79aedc.png)

**Comment by uoil** [comment]
Inside build.gradle you must change buildmode from IDE to RELEASE, remember to run gradle clean before you run gradle build, all of this info I've provided is in the readme

**Comment by PiotrekUnityDeveloper** [comment]
oh, yeah youre right. I didnt refreshed the gradle, thanks!

**Comment by uoil** [comment]
No problem, I know it's a little funky with gradle's build system.
