### ISSUE TITLE
Seppuku crashes for whatever reason lol

### ISSUE THREAD

**Issue by Lqnz** [seppukudevelopment/seppuku#96]
Hey!
So basically, it crashes for no reason at all (I've built it from source btw). I tried seppuku-3.1.8-full jar but it still crashes, I tried the pre-built one but it still crashes lol. Maybe because I am in Linux? idk but here's the crash log:

https://pastebin.com/NdBbLVpV

**Comment by sussyGaymer** [comment]
you seem to be missing some libraries, are you using the seppuku-full jar?

**Comment by uoil** [comment]
`java.lang.NoClassDefFoundError: org/json/simple/parser/JSONParser`

I'm using the same Linux Java version as you are, full jar contains the libraries and should work. Send crash log while using full jar if it happens again.

**Comment by Lqnz** [comment]
> `java.lang.NoClassDefFoundError: org/json/simple/parser/JSONParser`
> 
> I'm using the same Linux Java version as you are, full jar contains the libraries and should work. Send crash log while using full jar if it happens again.

Welp nvm, the full jar actually works now. Well thanks man!
