### ISSUE TITLE
Speed doesn't seem to work

### ISSUE THREAD

**Issue by Chicken01011** [seppukudevelopment/seppuku#97]
Doesn't even work in a single player world or a server with 0 anti cheat. Is there something else I need enabled for it to work or is it just broken?

**Comment by therealbush** [comment]
problema de la configuracciónes

**Comment by Bluecross-anarchy** [comment]
Hi @everyone :)

**Comment by uoil** [comment]
Try .speed and change modes for now, the ground speed will be updated in future patch. Timer as alternative as well
