### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Afelot** [seppukudevelopment/seppuku#99]
it won´t launch for some reason.

**Comment by rusnuker** [comment]
> it won´t launch for some reason.

Yeah, nice, but can you please provide logs or crash reports or something?

**Comment by Afelot** [comment]
can i provide screenshots. because i tried only launch the client alone and only gave me this 
![image](https://user-images.githubusercontent.com/113628615/190478345-415ec2c0-2e69-4fe1-b916-84956fa0474d.png)

**Comment by rusnuker** [comment]
go to Installations tab, your installation, click an icon with a folder, than go to crash-reports and upload the latest file here

**Comment by Afelot** [comment]
Do you mean this?
![image](https://user-images.githubusercontent.com/113628615/190487012-0ec48149-0433-4def-9067-6d454b850aef.png)

**Comment by Afelot** [comment]
[Uploading crash-2021-11-28_13.47.16-client.txt…]()

**Comment by Afelot** [comment]
[fml-crash-2022-07-15_21.07.45.txt](https://github.com/seppukudevelopment/seppuku/files/9578249/fml-crash-2022-07-15_21.07.45.txt)


this is weird l cant find latest crash

**Comment by rusnuker** [comment]
drop me your list of files in mods\ forler

**Comment by rusnuker** [comment]
Your mods\ folder contains unzip/unrar of a mod. Remove it and try again
